### ISSUE TITLE
Selection background color too similar to extension input box

### ISSUE THREAD

**Issue by lannonbr** [dericcain/feather-theme#2]
As seen below, I selected some text in the input box when searching for extensions and the background is too similar to contrast.

![screen shot 2018-08-01 at 9 13 32 am](https://user-images.githubusercontent.com/3685876/43523881-bd62de0c-956b-11e8-99d7-7b7ee7cbeb25.png)

**Comment by dericcain** [comment]
@lannonbr Good catch! I will try and update that soon and push some changes. Unless you want to give it a shot and submit a PR. Should be pretty easy.

**Comment by dericcain** [comment]
@lannonbr After looking into this, there is not a separate input box selection color. The only way to control selection would be to change the color of the selection for the entire theme. This is a limitation of VS Code theming. 

If you want to change the selection color to something different, you can add this to your settings.json:
```json
{
    "workbench.colorCustomizations": {
        "selection.background": "#00AA00" // whatever color you want here...
    }
}
```

I am going to close this issue for now, but feel free to carry on the conversation or make more recommendations.
